version: "2.1"
services:
  node:
    image: "arm32v7/node:17.8-alpine"
    container_name: "fact-bot"
    user: node:1002
    working_dir: "/home/node/app"
    environment:
      - "NODE_ENV=production"
    volumes:
      - "/opt/fact-bot/:/home/node/app"
    security_opt:
      - seccomp:unconfined
    command: npm run setup
    restart: always