version: "2.1"
services:
  node:
    image: "arm32v7/node:17.8-alpine"
    container_name: "fact-bot"
    user: node:1001
    working_dir: "/home/node/app"
    environment:
      - "NODE_ENV=production"
      - "IMAGES_DIR=/home/node/app/images"
      - "DATA_DIR=/home/node/app/data"
    volumes:
      - "./:/home/node/app"
    security_opt:
      - seccomp:unconfined
    command: npm run setup
    restart: always
